export default {
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CHANGE_EDIT_FIELD: 'CHANGE_EDIT_FIELD',
  RENAME_ITEM: 'RENAME_ITEM',
  CHANGE_ITEM_DESCRIPTION: 'CHANGE_ITEM_DESCRIPTION',
  CHANGE_ITEM_AUTHOR: 'CHANGE_ITEM_AUTHOR',
  CHANGE_SEARCH: 'CHANGE_SEARCH',
};